### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by netgfx** [mojaloop/contrib-fido2-flutter-lib#5]
Hello,

Is there any news about iOS support, if not what is exactly the stopper here? I might be able to contribute as I have seen that iOS 14 offers more options for face-id/touch-id for Webauthn.

**Comment by lewisdaly** [comment]
Hey @netgfx, we'd love to be able to support iOS here, it's just not on our radar at the moment as this component is only currently used for an internal demo. Right now I'm working on web support for flutter.

We'd love your contributions if you're happy to contribute to the library!

**Comment by netgfx** [comment]
thanks for the clarification. If I can find some time I'd be happy to contribute!
